//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RQL
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'binding' from namespace 'http://schemas.microsoft.com/soap-toolkit/wsdl-extension' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("SharpDevelop", "2.0.0.1710")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="XmlServerSoapBinding", Namespace="http://tempuri.org/RDCMSXMLServer/webservice/")]
    public partial class RDCMSXMLServer : System.Web.Services.Protocols.SoapHttpClientProtocol
    {
        
        /// <remarks/>
        public RDCMSXMLServer()
        {
            this.Url = "http://REDDOT:80/CMS/webservice/RDCMSXMLServer.WSDL";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://tempuri.org/RDCMSXMLServer/action/XmlServer.Execute", RequestNamespace="http://tempuri.org/RDCMSXMLServer/message/", ResponseNamespace="http://tempuri.org/RDCMSXMLServer/message/")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string Execute(string sParamA, ref object sErrorA, ref object sResultInfoA)
        {
            object[] results = this.Invoke("Execute", new object[] {
                        sParamA,
                        sErrorA,
                        sResultInfoA});
            sErrorA = ((object)(results[1]));
            sResultInfoA = ((object)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginExecute(string sParamA, object sErrorA, object sResultInfoA, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("Execute", new object[] {
                        sParamA,
                        sErrorA,
                        sResultInfoA}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndExecute(System.IAsyncResult asyncResult, out object sErrorA, out object sResultInfoA)
        {
            object[] results = this.EndInvoke(asyncResult);
            sErrorA = ((object)(results[1]));
            sResultInfoA = ((object)(results[2]));
            return ((string)(results[0]));
        }
    }
}
